sudo: required
matrix:
  include:
  - os: linux
    jdk: oraclejdk8
    language: generic
    before_install:
    - sudo add-apt-repository ppa:maarten-fonville/protobuf -y
    - sudo apt-get update -y
    - sudo apt-get install libprotobuf-dev libprotoc-dev protobuf-compiler -y
    script: gradle/buildViaTravis-linux.sh
  - os: osx
    osx_image: xcode9.3
    language: generic
    env: LDFLAGS="/usr/local/lib/libprotobuf.a /usr/local/lib/libprotoc.a"
    before_install:
    - rm -rf '/usr/local/lib/python2.7/site-packages/numpy/__config__.py'
    - rm -rf '/usr/local/bin/2to3-2'
    - brew update
    - brew upgrade
    - brew upgrade python
    - EDITOR="sed -i '' 's/system \".\/configure\",/system \".\/configure\", \"--disable-shared\",/g'" brew edit protobuf
    - brew install protobuf
    script: gradle/buildViaTravis.sh

before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
notifications:
  email: false
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.m2"

env:
  global:
  - secure: fG6x4/LuQuYDO6B3hw9YnxTKBepOS/zcSqDbyl3fJkYSDYuRS6yvI0CsQCQGTLtD3MKED+0o43rUiuPgNzz3qENKQukrFgmXQl24fwuUxtFhz4Lbb3OCMnWMAU3SgWZmpbUoOhCEGr0LzvYnb+MImiRU2v7gxr4Nc9hy8gRZjQQ4R7V+UlhOhZVjN5JfsEnKMpZejEkFlNADCdAhSDdHLVZN7lOsFjDC7XQ/GKLKGrRyIzREto9hm58QIsolghMyIEL2Jj1+ePTM/3wCYLUaRpdUjmHQawJi9vfwFO4g4yyKdUVXHpITQwQ7JE/SoJsje8ZUhOJZ3TvaBDlVjvXP41P3JNDbSesrBYcR0k70TYr7wliHKsdGurHvDQ/2Rxas/FITFGvLchYczbUPLJ7h0fJha+cpwsmmNvLmg0RIaaHa4RXPknWuetipbJFSqYtBN01iCtdSzHwwhZGZ6zV3kPBa0QWsDLWa/Ih2STDY6DVIA6YgaqaM6aN9U/UR8XeCnjPot+StaNuU2nSgGcwX5BIZRMuca9OF6FryG+t527njU86mp2QSj1HOTs/c31v9sSg2krCl7jChm3ZtpXyiEp+IdKaa5uZHLyx0fcm489375PLjhE6gRp/zvYf58uSvoMLOl1xwfOkNiPP8YXIDtVodzgGxCnxD49WE5B9CCbk=
  - secure: NvHtXfxiqBwkmj5l7Wr9EuBi9X0dMVL5CCeKFVqzIOmXCIdjwvknQ3rfZZ46fjwOQC/FuCcoM/8dHkBIkGzqIVo9Qx1+AGnq4AO7rr+iLYPvmz2wB8QKrD81bVAhtoKnuYe1wyu1XvURBgrietjoAgxrhgW3iReBVW4dj0YaTdRZXAD70M3i63tfV9GyB2pv6NfRyaq50IGkaJPdiyUPpDWcSmtnrkxQvUvIzNm50AGKEq3IuLp+wgVouAI81m1a+B0TuEfo4VnqOKlJx1dq9VT76GN4Ni+u2Rnnli2kFAXGtGfuPrZF1WPE2APJQ4W9H7YeGzya38JCUkkwD2Buxoe7CsW7ZEVnGbFE4xsuc+vejvDkeGF4LLABzuGwcDxG70MPHoXpyd1ayY3Iek1zPn4/3nFTO40YreeaHDT3MG3BSZx6WkMfmqfnFsKJeX9g7zzZLGmOuniwGLOIwFpePtyhn/wQvfPG+UalnSk+pXyGWuhnurcgDlk7ASlHj4TZnDiZvCCZy1xdzytttwf/i71Ts+6Db+TZfggnymeYFRo19UpLTr15Rdkwk0CNrJlvruKkGkR5G2els14M37PhHaeIdGol3ZqARs9+7o9gnRW2cPaQ26IRgNSGQwRhGaJcAyoLNZejc97OHEga9r6B8cIJK6NGD+4m8GA7Sh4O3EM=
